db:
  #image: postgis
  build: ../docker-postgis
  hostname: db
  environment:
    - USERNAME=docker
    - PASS=docker
    - HSTORE=true
    
imposm:
  #image: imposm
  build: ../docker-imposm3
  volumes:
    - ./base-pbf:/home/base-pbf
    - ./import-done:/home/import-done
    - ./import-queue:/home/import-queue
    - ./settings:/home/settings
    - ./cache:/home/cache
  links:
    - db:db
  environment:
    - user=docker
    - password=docker
    - port=5432
    - host=db
    - dbname=gis
    
osmupdate:
  #image: osmupdate
  build: ../docker-osmupdate
  volumes:
    - ./base-pbf:/home/base-pbf
    - ./import-done:/home/import-done
    - ./import-queue:/home/import-queue
    - ./settings:/home/settings
    
