storage:
  build: osm-storage
  hostname: storage
  volumes:
    - ../docker-osmupdate/base_pbf:/home/base_pbf
    - ./settings:/home/settings

db:
  #image: postgis
  build: ../docker-postgis
  hostname: db
  environment:
    - USERNAME=docker
    - PASS=docker
    - HSTORE=true

imposm:
  #image: imposm
  build: ../docker-imposm3
  volumes_from:
    - storage
  links:
    - db:db
  environment:
    - USER=docker
    - PASSWORD=docker
    - PORT=5432
    - HOST=db
    - DATEBASE=gis

osmupdate:
  #image: osmupdate
  build: ../docker-osmupdate
  volumes_from:
    - storage
