storage:
  image: ubuntu:latest
  hostname: storage
  volumes:
    # These are sharable to other containers
    - ./osm_pbf:/home/osm_pbf
    - ./settings:/home/settings
    - /home/import_done
    - /home/import_queue
    - /home/cache

db:
  image: kartoza/postgis
  hostname: db
  environment:
    - USERNAME=docker
    - PASS=docker
    # - HSTORE=true

imposm:
  image: kartoza/imposm
  volumes_from:
    - storage
  links:
    - db:db
  environment:
    - USER=docker
    - PASSWORD=docker
    - PORT=5432
    - HOST=db
    - DATEBASE=gis
    # in seconds
    - TIME=120

osmupdate:
  image: etrimaille/osmupdate
  volumes_from:
    - storage
  environment:
    # in seconds
    - TIME=120
